### ISSUE TITLE
npm install failed

### ISSUE THREAD

**Issue by iivveess** [wechaty/openapi#7]
Env:
- Mac
- Cmd - `npm install wechaty-openapi`
- npm version - 7.6.1

Fail to Install `npm install wechaty-openapi`
Error log:
```5783 timing command:install Completed in 27244ms
5784 verbose stack Error: 404 Not Found - GET https://cdn.npm.taobao.org/wechaty-openapi/-/wechaty-openapi-0.1.0.tgz
5784 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/npm-registry-fetch/check-response.js:123:15
5784 verbose stack     at runMicrotasks (<anonymous>)
5784 verbose stack     at processTicksAndRejections (internal/process/task_queues.js:93:5)
5785 verbose statusCode 404
5786 verbose pkgid wechaty-openapi@https://registry.npm.taobao.org/wechaty-openapi/-/wechaty-openapi-0.1.0.tgz
5787 verbose cwd /Users/ives/code/work_foxconn/fimo-wechaty-noc
5788 verbose Darwin 20.3.0
5789 verbose argv "/usr/local/Cellar/node/14.11.0/bin/node" "/usr/local/bin/npm" "install" "wechaty-openapi"
5790 verbose node v14.11.0
5791 verbose npm  v7.6.1
5792 error code E404
5793 error 404 Not Found - GET https://cdn.npm.taobao.org/wechaty-openapi/-/wechaty-openapi-0.1.0.tgz
5794 error 404
5795 error 404 'wechaty-openapi@https://registry.npm.taobao.org/wechaty-openapi/-/wechaty-openapi-0.1.0.tgz' is not in the npm registry.
5796 error 404 You should bug the author to publish it (or use the name yourself!)
5797 error 404 Note that you can also install from a
5798 error 404 tarball, folder, http url, or git url.
5799 verbose exit 1```

**Comment by huan** [comment]
I can install it without any problem:

```sh
$ npm install wechaty-openapi

> grpc@1.24.6 install /tmp/t/node_modules/grpc
> node-pre-gyp install --fallback-to-build --library=static_library

node-pre-gyp WARN Using needle for node-pre-gyp https download 
[grpc] Success: "/tmp/t/node_modules/grpc/src/node/extension_binary/node-v72-linux-x64-glibc/grpc_node.node" is installed via remote

> protobufjs@6.10.2 postinstall /tmp/t/node_modules/@grpc/proto-loader/node_modules/protobufjs
> node scripts/postinstall

npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN t@1.0.0 No description
npm WARN t@1.0.0 No repository field.

+ wechaty-openapi@0.1.0
added 207 packages from 147 contributors and audited 207 packages in 27.486s

4 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```

**Comment by iivveess** [comment]
I got it, I'll check it tomorrow, thanks for the info.

**Comment by iivveess** [comment]
@huan 
Yes, you're right.
Once I designated the registry to the original one, the problem solved.
`npm config set registry https://registry.npmjs.org/`
